language: java
cache:
  directories:
  - "$HOME/.m2"
  - frontend/node
  - frontend/node_modules
jdk: oraclejdk8
install: "/bin/true" # workaround https://github.com/Swagger2Markup/swagger2markup-maven-plugin/pull/24
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - (cd docker; docker-compose up -d)
after_acript:
  - "sh -e /etc/init.d/xvfb stop"
  - (cd docker; docker-compose down)
script:
  # if there isn't pointed explicitly PhantomJS will be used by default for webdriver integration test and all 3 for js unit test
  - "./mvnw -Dkarma.browsers=Chrome,PhantomJS -P frontend clean package"
  - "./mvnw -Dkarma.browsers=Firefox -Dcustom.selenium.browser=FIREFOX -P frontend clean package"
#  - "./mvnw -Dkarma.browsers=Chrome -Dcustom.selenium.browser=CHROME -P frontend clean package"
addons:
  firefox: "55.0.1"
  chrome: stable