sudo: required
dist: trusty

language: java
cache:
  directories:
  - "$HOME/.m2"
  - frontend/node
  - frontend/node_modules
jdk: oraclejdk9
services:
  - docker
before_install:
#  - sudo apt-get install -y chromium-browser #https://www.ubuntuupdates.org/pm/google-chrome-stable
  - openssl aes-256-cbc -K $encrypted_8518ee46cc9c_key -iv $encrypted_8518ee46cc9c_iv -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
install: "/bin/true" # workaround https://github.com/Swagger2Markup/swagger2markup-maven-plugin/pull/24
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
after_acript:
script:
  - (cd docker; docker-compose up -d)
  # if there isn't pointed explicitly PhantomJS will be used by default for both webdriver integration test and js unit test
  # We use 'install' phase because of use jars in subsequent tests
  - ./mvnw -P frontend -P jacoco -P docker -P webdriver-chrome -P webdriver-firefox -Dcustom.selenium.headless=true clean install --no-snapshot-updates
  - (cd docker; docker-compose down)
  - docker pull nkonev/rendertron-docker
  - ./mvnw -pl deploy-test -P deploy-test clean test  --no-snapshot-updates
  - rm -rf ~/.m2/repository/com/github/nkonev/blog
  - bash <(curl -s https://codecov.io/bash)
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_TEST_RESULT" == "0" && "$TRAVIS_EVENT_TYPE" != "cron" ]]; then (
      echo "Will push docker image";
      docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD";
      docker push nkonev/blog:latest;
      docker push nkonev/blog:$(cat backend/target/VERSION);

      ssh -o "BatchMode yes" -o StrictHostKeyChecking=no -q $CONNECT_LINE $UPDATE_COMMAND;
    ) else (
      echo "Won't push docker image and deploy";
    ) fi
addons:
  firefox: "57.0"
  chrome: stable
