version: '2.1'

services:
  blog-service:
    restart: unless-stopped
    image: nikit007/blog:latest
    build:
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
