version: '2.1'

services:
  blog-service:
    restart: unless-stopped
    build:
      context: .
    environment:
      liquibase.drop-first: 'true'
      liquibase.contexts: 'main,test'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
