version: '3.2'

services:
  blog:
    image: nkonev/blog:latest
    logging:
      driver: "journald"
      options:
        tag: blog
    deploy:
      replicas: 2
    environment:
      # https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts
      # https://blogs.oracle.com/poonam/about-g1-garbage-collector%2c-permanent-generation-and-metaspace
      - _JAVA_OPTIONS=-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=256M -XX:OnOutOfMemoryError="kill -9 %p"
      - liquibase.contexts=main,test
      - custom.stomp.broker.host=rabbitmq
      - custom.stomp.broker.port=61613
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/blog?connectTimeout=10
      - spring.redis.url=redis://redis:6379/0
    ports:
      - 8000:8080
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8090:8080
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging:
      driver: "journald"
      options:
        tag: visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
  postgresql:
    image : postgres:10.0
    hostname: postgresql
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    volumes :
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgresql_blog_dev_data_dir:/var/lib/postgresql/data
    logging:
      driver: "journald"
      options:
        tag: postgresql
    deploy:
      placement:
        constraints: [node.labels.blog.server.role == db]

  redis:
    image: redis:4.0.2
    hostname: redis
    ports:
      - 26379:6379
    volumes :
      - redis_blog_dev_data_dir:/data
    logging:
      driver: "journald"
      options:
        tag: redis
    deploy:
      placement:
        constraints: [node.labels.blog.server.role == db]

  rabbitmq:
    image : nkonev/rabbitmq-web-stomp:3.6.12
    hostname: rabbitmq
    ports:
      - 45672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=blog
      - RABBITMQ_DEFAULT_PASS=blogPazZw0rd
    volumes :
      - rabbitmq_data_dir:/var/lib/rabbitmq/mnesia
    logging:
      driver: "journald"
      options:
        tag: rabbitmq
    deploy:
      placement:
        constraints: [node.labels.blog.server.role == db]

volumes:
  #enviroment
  postgresql_blog_dev_data_dir:
  redis_blog_dev_data_dir:
  rabbitmq_data_dir:
