version: '2.1'

services:
  blog-1:
    extends:
      file: common.yml
      service: blog-service
    environment:
      liquibase.drop-first: 'true'
      liquibase.contexts: 'main,test'
    ports:
      - 8081:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.101
  blog-2:
    extends:
      file: common.yml
      service: blog-service
    environment:
      liquibase.enabled: 'false'
    ports:
      - 8082:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.102
