version: '2.1'

services:
  #enviroment
  postgresql:
    image : postgres:${POSTGRESL_VERSION}
    hostname: postgresql
    # имена контейнеров не должны пересекаться с уже существующими
    container_name: postgresql-blog-dev
    restart: unless-stopped
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    volumes :
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgresql_blog_dev_data_dir:/var/lib/postgresql/data
    networks:
      blog-dev:
        ipv4_address: 172.22.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  redis:
    image: redis:${REDIS_VERSION}
    hostname: redis
    container_name: redis-blog-dev
    restart: unless-stopped
    ports:
      - 26379:6379
    volumes :
      - redis_blog_dev_data_dir:/data
    networks:
      blog-dev:
        ipv4_address: 172.22.0.3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  rabbitmq:
    # image : rabbitmq:3.6.11-management
    build:
      context: ./rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq-blog-dev
    ports:
      - 45672:15672
      - 35672:5672
      - 60613:61613
      - 35674:15674
    environment:
      - RABBITMQ_DEFAULT_USER=blog
      - RABBITMQ_DEFAULT_PASS=blogPazZw0rd
    volumes :
      - rabbitmq_data_dir:/var/lib/rabbitmq/mnesia
    networks:
      blog-dev:
        ipv4_address: 172.22.0.4
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  #enviroment
  postgresql_blog_dev_data_dir:
  redis_blog_dev_data_dir:
  rabbitmq_data_dir:

networks:
  blog-dev:
    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "true"
#      com.docker.network.bridge.enable_ip_masquerade: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
        gateway: 172.22.0.1
