version: '2.1'

services:
  blog-1:
    restart: unless-stopped
    image: nkonev/blog:latest
    container_name: blog-1
    logging:
      driver: "journald"
    ports:
      - 8081:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.101
  blog-2:
    restart: unless-stopped
    image: nkonev/blog:latest
    container_name: blog-2
    logging:
      driver: "journald"
    ports:
      - 8082:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.102
