# This file used for both developer and demo purposes.
# It contains environment
version: '3.2'

services:
  #enviroment
  postgresql:
    image : postgres:11-beta3
    hostname: postgresql
    container_name: postgresql-blog-dev
    restart: unless-stopped
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    volumes :
      - ./postgresql_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgresql_blog_dev_data_dir:/var/lib/postgresql/data
    networks:
      blog-dev:
        ipv4_address: 172.22.0.2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  redis:
    image: redis:5.0-rc3
    hostname: redis
    container_name: redis-blog-dev
    restart: unless-stopped
    ports:
      - 26379:6379
    volumes :
      - redis_blog_dev_data_dir:/data
    networks:
      blog-dev:
        ipv4_address: 172.22.0.3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  rabbitmq:
    image : nkonev/rabbitmq-web-stomp:3.7.6
    hostname: rabbitmq
    container_name: rabbitmq-blog-dev
    restart: unless-stopped
    ports:
      - 45672:15672
      - 35672:5672
      - 60613:61613
      - 35674:15674
    environment:
      - RABBITMQ_DEFAULT_USER=blog
      - RABBITMQ_DEFAULT_PASS=blogPazZw0rd
    volumes :
      - rabbitmq_data_dir:/var/lib/rabbitmq/mnesia
    networks:
      blog-dev:
        ipv4_address: 172.22.0.4
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  #enviroment
  postgresql_blog_dev_data_dir:
  redis_blog_dev_data_dir:
  rabbitmq_data_dir:

networks:
  blog-dev:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
