version: '2.1'

services:
  blog-1:
    restart: unless-stopped
    image: nikit007/blog:latest
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
    ports:
      - 8081:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.101
  blog-2:
    restart: unless-stopped
    image: nikit007/blog:latest
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
    ports:
      - 8082:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.102
