version: '2.1'

services:
  blog-1:
    extends:
      file: common.yml
      service: blog-service
    ports:
      - 8081:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.101
  blog-2:
    extends:
      file: common.yml
      service: blog-service
    ports:
      - 8082:8080
    networks:
      blog-dev:
        ipv4_address: 172.22.0.102

  nginx:
    image: nginx:1.13.3
    hostname: nginx
    container_name: nginx-blog
    ports:
     - 8000:80
    volumes:
     - ./nginx/etc/nginx/crypt:/etc/nginx/crypt
     - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      blog-dev:
        ipv4_address: 172.22.0.50

