logging.level.: INFO
#logging.level.org.springframework.security: DEBUG
#logging.level.org.springframework.session: DEBUG
#logging.level.org.springframework.security.web: DEBUG
#logging.level.org.apache.catalina: TRACE
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type: TRACE


server.tomcat.accesslog.enabled: true
server.tomcat.accesslog.pattern: '%t %a "%r" %s (%D ms)'
server.tomcat.basedir: ${java.io.tmpdir}/com.github.nikit.cpp.tomcat
server.session.store-dir: ${server.tomcat.basedir}/sessions

# this is URL
spring.mvc.static-path-pattern: /**
# You need to remove "file:..." element for production or you can to remove spring.resources.static-locations
# first element - for eliminate manual restart app in IntelliJ for copy compiled js to target/classes, last slash is important,, second element - for documentation
spring.resources.static-locations: file:frontend/src/main/resources/static/, classpath:/static/

