logging.level.: INFO
#logging.level.org.springframework.security: DEBUG
#logging.level.org.springframework.session: DEBUG
#logging.level.org.springframework.security.web: DEBUG
#logging.level.org.apache.catalina: TRACE
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type: TRACE


server.tomcat.accesslog.enabled: true
server.tomcat.accesslog.pattern: '%t %a "%r" %s (%D ms)'
server.tomcat.basedir: ${java.io.tmpdir}/com.github.nikit.cpp.tomcat

spring.devtools.restart.additional-paths: ${custom.frontend.resources}
custom.frontend.resources: frontend/src/main/resources
# disable(set to one) default unused static locations in favor to WebConfig#addResourceHandlers
# spring.resources.static-locations: classpath:/public/
