logging.level.: INFO
#logging.level.org.springframework.security: DEBUG
#logging.level.org.springframework.session: DEBUG
#logging.level.org.springframework.security.web: DEBUG
#logging.level.org.apache.catalina: TRACE
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type: TRACE


server.tomcat.accesslog.enabled: true
server.tomcat.accesslog.pattern: '%t %a "%r" %s (%D ms)'
server.tomcat.basedir: ${java.io.tmpdir}/com.github.nikit.cpp.tomcat

custom.static.location: frontend/src/main/resources/static/
spring.devtools.restart.additional-paths: ${custom.static.location}
# this is URL
spring.mvc.static-path-pattern: /**
# You need to set "classpath:/static/" resources instead "file:" for production
# last slash is important,
# first element - for eliminate manual restart app in IntelliJ for copy compiled js to target/classes, second element - for documentation
spring.resources.static-locations: file:${custom.static.location}, classpath:/static/

