groups:
- name: exporter
  rules:
  - alert: Exporter instance down
    expr: up == 0
#    for: 5m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

- name: prerender
  rules:
  - alert: Prerender not renders html page
    expr: probe_success{job="prerender"} == 0
#    for: 5m
    labels:
      severity: page
    annotations:
      summary: "Prerender not renders html page"
      description: "Please check if prerender alive & blackbox exporter send correct useragent which configured in java blog application too"

- name: blog_log_events
  rules:
  - alert: Increasing blog app errors
    expr: increase(logback_events_total{level="error"}[30s]) > 0
    labels:
      severity: page
    annotations:
      summary: "Errors count is increasing for 30s"
      description: "Please check application logs"
  - alert: Increasing blog app warnings
    expr: increase(logback_events_total{level="warn"}[30s]) > 0
    labels:
      severity: page
    annotations:
      summary: "Warnings count is increasing for 30s"
      description: "Please check application logs"

- name: node
  rules:
  - alert: "CPU > 80%"
    expr: 1-irate(node_cpu{job="node-exporter",mode="idle"}[1h]) > 0.8
    for: 3m
    labels:
      severity: page
    annotations:
      summary: "CPU > 80%"
      description: "Please check top"
  - alert: "Disk > 90%"
    expr: 1-((node_filesystem_avail_bytes{mountpoint="/rootfs"}) / node_filesystem_size_bytes{mountpoint="/rootfs"})>0.9
    for: 1m
    labels:
      severity: high
    annotations:
      summary: "Disk > 90%"
      description: "Please cleanup disks"