# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:

- job_name: node-exporter
  dns_sd_configs:
  - names:
    - tasks.node_exporter
    refresh_interval: 30s
    type: A
    port: 9100

- job_name: postgres
  metrics_path: /metrics
  static_configs:
    - targets:
      - postgresql_exporter:9187

- job_name: rabbitmq
  metrics_path: /metrics
  static_configs:
    - targets:
      - rabbitmq_exporter:9191

- job_name: redis
  metrics_path: /metrics
  static_configs:
    - targets:
      - redis_exporter:9121

- job_name: blog
  metrics_path: /actuator/prometheus
  dns_sd_configs:
  - names:
    - tasks.blog
    refresh_interval: 30s
    type: A
    port: 3010
# https://github.com/prometheus/blackbox_exporter/blob/master/README.md
# wget -O - 'http://localhost:9115/probe?target=https://nkonev.name&module=get_as_prometheus'
- job_name: 'rendertron'
  metrics_path: /probe
  params:
    module: ['get_as_prometheus']
    target: ['http://blog:8098']
  static_configs:
    - targets:
      - blackbox_exporter:9115

- job_name: traefik
  static_configs:
    - targets:
      - traefik:8080

rule_files:
  - /etc/prometheus/alerting.yml

# https://github.com/prometheus/alertmanager
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
